# Generated by Django 5.0.13 on 2025-04-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_entry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='diary.lifechapter'),
        ),
    ]
