# Generated by Django 5.2 on 2025-04-22 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_entry_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_style', models.CharField(choices=[('reflective', 'Reflective'), ('analytical', 'Analytical'), ('creative', 'Creative'), ('concise', 'Concise'), ('detailed', 'Detailed'), ('poetic', 'Poetic'), ('humorous', 'Humorous')], default='reflective', max_length=30)),
                ('tone', models.CharField(choices=[('positive', 'Mostly Positive'), ('balanced', 'Balanced'), ('realistic', 'Realistic'), ('growth', 'Growth-focused')], default='balanced', max_length=30)),
                ('focus_areas', models.CharField(blank=True, help_text='Comma-separated areas to emphasize (e.g., personal growth,relationships)', max_length=255)),
                ('language_complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('advanced', 'Advanced')], default='moderate', max_length=20)),
                ('include_questions', models.BooleanField(default=True, help_text='Include reflective questions at the end of entries')),
                ('metaphor_frequency', models.CharField(choices=[('minimal', 'Minimal'), ('occasional', 'Occasional'), ('frequent', 'Frequent')], default='occasional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
