# Generated by Django 5.2 on 2025-04-23 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinsight',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='userinsight',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='userinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinsight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinsight',
            name='insight_type',
            field=models.CharField(choices=[('mood_analysis', 'Mood Analysis'), ('pattern', 'Pattern Detection'), ('suggestion', 'Suggestion'), ('topic_analysis', 'Topic Analysis')], max_length=50),
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag_type', models.CharField(choices=[('topic', 'Topic'), ('mood', 'Mood'), ('person', 'Person'), ('location', 'Location'), ('other', 'Other')], default='topic', max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='diary.entry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
