# Generated by Django 5.2 on 2025-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_userinsight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='chapters_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
