# Generated by Django 5.0.13 on 2025-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.tag'),
        ),
    ]
