# Generated by Django 5.2 on 2025-04-24 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_userfollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifechapter',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='lifechapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifechapter',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifechapter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifechapter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lifechapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lifechapter',
            name='color',
            field=models.CharField(default='indigo', max_length=50),
        ),
    ]
