# Generated by Django 5.2 on 2025-05-23 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_entryphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='published_in_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_entries', to='diary.journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='entry_count_cached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='first_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='last_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='like_count_cached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='journal',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='marketplace_tags',
            field=models.ManyToManyField(blank=True, to='diary.journaltag'),
        ),
        migrations.CreateModel(
            name='JournalLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_likes', to='diary.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'journal')},
            },
        ),
        migrations.CreateModel(
            name='JournalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='diary.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'journal')},
            },
        ),
        migrations.CreateModel(
            name='JournalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='diary.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'journal')},
            },
        ),
    ]
