"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'diaryvault.com', 'www.diaryvault.com', '52.64.254.25']

# API Keys
GROK_API_KEY = os.getenv('GROK_API_KEY')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'diary',
    'widget_tweaks',
    'django.contrib.sites',

    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.microsoft',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'diary.middleware.RateLimitMiddleware',
    'diary.middleware.PendingEntryMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Custom adapters for auto-username generation
ACCOUNT_ADAPTER = 'diary.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'diary.adapters.CustomSocialAccountAdapter'

SOCIALACCOUNT_FORMS = {}

# Enhanced social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Skip signup form entirely
SOCIALACCOUNT_SIGNUP_FORM_CLASS = None  # No signup form
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Don't require email verification
SOCIALACCOUNT_EMAIL_REQUIRED = False  # Don't require email in signup form
SOCIALACCOUNT_QUERY_EMAIL = True  # Always fetch email from provider

# Social account settings (if using social login)
SOCIALACCOUNT_LOGIN_ON_GET = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add these django-allauth specific settings
ACCOUNT_LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/dashboard/'

# Enhanced allauth configuration
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False  # Don't require username in forms (we auto-generate)
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # No email verification required
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_ON_GET = False  # Require POST for logout (security)
ACCOUNT_SESSION_REMEMBER = True  # Remember login sessions

SOCIALACCOUNT_STORE_TOKENS = False

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'microsoft': {
        'tenant': 'f3f2b81d-748f-4408-9eb7-6b7afbaa488e',  # Your Microsoft Tenant ID
        'SCOPE': [
            'User.Read',
            'email',
            'profile',
        ],
    },
    'apple': {
        # Apple configuration (when you get credentials)
        'certificate_key': '''-----BEGIN PRIVATE KEY-----
        # Your Apple certificate key will go here
        -----END PRIVATE KEY-----''',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')

# Marketplace Settings
MARKETPLACE_SETTINGS = {
    'PLATFORM_FEE_PERCENT': 10,  # 10% platform fee
    'TIP_FEE_PERCENT': 5,        # 5% fee on tips
    'MINIMUM_PAYOUT': 50.00,     # Minimum earnings before payout
    'PAYOUT_SCHEDULE': 'monthly', # monthly, weekly, daily
}

# Celery for background tasks
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379')

# Enhanced Marketplace Features (2025)
MARKETPLACE_ENHANCED = {
    'DYNAMIC_PRICING_ENABLED': True,
    'ANALYTICS_PACKAGES_ENABLED': True,
    'PREMIUM_PLACEMENTS_ENABLED': True,
    'SUBSCRIPTION_TIERS_ENABLED': True,

    # Analytics package pricing
    'ANALYTICS_PRICING': {
        'basic_insights': 9.99,
        'advanced_analytics': 19.99,
        'market_intelligence': 39.99
    },

    # Revenue sharing based on subscription tier
    'REVENUE_SHARING': {
        'standard': 0.85,        # 85% to author
        'author_starter': 0.90,  # 90% to author
        'author_professional': 0.95,  # 95% to author
    }
}

# Celery periodic tasks for automation
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update-dynamic-pricing': {
        'task': 'diary.tasks.update_dynamic_pricing',
        'schedule': crontab(hour=2, minute=0),  # Daily at 2 AM
    },
    'process-monthly-payouts': {
        'task': 'diary.tasks.process_monthly_payouts',
        'schedule': crontab(day_of_month=1, hour=3, minute=0),  # 1st of month
    },
    'generate-marketplace-insights': {
        'task': 'diary.tasks.generate_marketplace_insights',
        'schedule': crontab(hour=1, minute=0, day_of_week=1),  # Weekly Monday
    },
}
